### ISSUE TITLE
Flush lists can be randomly deleted, leading to a stale cache

### ISSUE THREAD

**Issue by BertrandBordage** [django-cache-machine/django-cache-machine#107]
django-cache-machine assumes that its flush lists are always in cache as long as the queries it references are also in cache.
Unfortunately, this is not true because Least Recently Used caches like memcached and Redis are not implemented ideally because performance would be terrible. When the cache is full, they just fetch a few random keys and delete from that batch the ones with the earliest expiration. This means that any key can be deleted at any time, whatever its timeout can be.
Of course, this leads to stale data: if the cache key for one query is still here while the corresponding flush list has been deleted, django-cache-machine still serves the cached results and it will only stop once it has expired.

For more detail, read [the article about that in the Redis docs](http://redis.io/topics/lru-cache) and [the analysis I wrote on this issue in django-cache-machine](http://django-cachalot.readthedocs.org/en/latest/introduction.html#id2).

**Comment by tobiasmcnulty** [comment]
Thanks for the link!
