### ISSUE TITLE
Using a custom name of a field in serializer raises TypeError Exception

### ISSUE THREAD

**Issue by sacgup** [django-cache-machine/django-cache-machine#110]
I wanted to have a different name for a foreign field in serializer while creation. Basically 'topic_id' instead of 'topic'.

So I did this in my serializer.

```
topic_id = serializers.PrimaryKeyRelatedField(source='topic', queryset=Topic.objects.all(), required=False)
```

which worked fine for me till I started using Cache Machine.

After which it gives me following error while creating.

```
 {
  "topic_id": [
    "Incorrect type. Expected pk value, received int."
  ]
}
```

It happens only when i change the manager of `Topic` model to `CachingManager`

```
class Topic(models.Model, CachingMixin):
     objects = CachingManager()
```

If i remove the CachingManager, it works fine. Caching manager is somehow altering the queryset or something else and getting this exception.

I printed the exception in PrimaryRelatedField. It occurs at this point. 

```
q =  self.get_queryset()
```

Exception is `TypeError` and exception message is int() argument must be a string or a number, not 'object'

**Comment by tobiasmcnulty** [comment]
I think you have your mixin order backwards. You want this:

    class Topic(CachingMixin, models.Model):

See: https://stackoverflow.com/questions/10018757/how-does-the-order-of-mixins-affect-the-derived-class
