### ISSUE TITLE
Count on queryset with empty list fails

### ISSUE THREAD

**Issue by andymckay** [django-cache-machine/django-cache-machine#14]
For example in amo:

>>> Addon.objects.filter(id__in=[])
[]

>>> User.objects.filter(id__in=[]).count()
0

>>> Addon.objects.filter(id__in=[]).count()
[...snip]

/Users/andy/sandboxes/zamboni/vendor/src/django/django/db/models/sql/where.pyc in make_atom(self, child, qn, connection)
    177         if lookup_type == 'in':
    178             if not value_annot:
--> 179                 raise EmptyResultSet
    180             if extra:
    181                 return ('%s IN %s' % (field_sql, extra), params)

EmptyResultSet:

Doing a where lookup on an empty list means that as_sql throws an error. Presumably because doing an IN () is invalid SQL. Because as_sql is used by cache machine to figure out the query_key, the counts fail. 

Not sure what the right answer here is, since counts with and EmptyResultSet are always zero, that can be special cased in cache machine.

**Comment by tobiasmcnulty** [comment]
This appears to be fixed now - feel free to open if that's no longer the case.
