### ISSUE TITLE
No way configure Django-Cache-Machine to use Multiple Memcache Nodes?

### ISSUE THREAD

**Issue by lylepratt** [django-cache-machine/django-cache-machine#28]
I doesn't seem like there is a way to configure Django-Cache-Machine to use multiple memecache nodes. I'm trying to use it with Amazon's Elasticache with no success. Is this an issue or am I completely missing something (very likely...)?

Many thanks!
Lyle

**Comment by jayeshbadgujar** [comment]
Why use Djanog Memcached
