### ISSUE TITLE
New pypi release and version bump?

### ISSUE THREAD

**Issue by chaselee** [django-cache-machine/django-cache-machine#53]
Looks like the last release was May 2013 and doesn't include the Django 1.6 updates. Time to ring in the new year?

**Comment by mkuchen** [comment]
@jbalogh could you do a pypi version release for Django 1.7 support?  We're looking to upgrade and noticed there hasn't been one in a while :)

**Comment by tobiasmcnulty** [comment]
I just tagged a new minor release (0.8.1) with some of the recent changes, including Django 1.7 and 1.8 support. You can find it on PyPI and checkout the release notes on GitHub or RTD:

http://cache-machine.readthedocs.org/en/latest/releases.html#v0-8-1-2015-07-03
