### ISSUE TITLE
Caching Consistency if DB is used by few Django apps

### ISSUE THREAD

**Issue by Voulnet** [django-cache-machine/django-cache-machine#55]
Hello. I have 3 django apps sharing the same database.

Will they all share the same consistent cache? 

If an item is modified by app1, will the other apps still get a consistent cache?

Note that the other apps will just import the models from app1 (including of course Cache Machine object managers), so I would like to know if the behavior will be as expected.

Thanks

**Comment by tobiasmcnulty** [comment]
If all of your django-cache-machine settings are the same for each app, you're using the same models, and all the apps share a single cache instance and single database, I believe it will use the same cached objects.  If your apps use different databases you'll want to make sure you're using a different cache as well to avoid conflicts between the apps (or configure your ``CACHE_PREFIX`` appropriately).
