### ISSUE TITLE
Adding an object did not invalidate queries

### ISSUE THREAD

**Issue by twidi** [django-cache-machine/django-cache-machine#6]
I had a strange issue on my site and i made some test and it seems that when adding an object of a model, invalidation is not done for queries like all()
Of course the all query (or other) is invalidated when an object is updated.

Exemple: 

    from django.db import models
    import caching.base
    class MyTest(caching.base.CachingMixin, models.Model):
      vartest = models.IntegerFields()
      objects = caching.base.CachingManager()
      def __repr__:
        return '<MyTest(id=%d, var=%d)>' % (self.id, self.vartest)

Then in a python/django shell:

    MyTest.objects.create(vartest=1)
    => <MyTest(id=1, var=1)>
    MyTest.objects.all()
    => [<MyTest(id=1, var=1)>]
    MyTest.objects.create(vartest=2)
    => <MyTest(id=2, var=2)>
    MyTest.objects.all()
    => [<MyTest(id=1, var=1)>]

    t=MyTest.objects.get(id=1)
    t.vartest=3
    t.save()
    t
    => <MyTest(id=1, var=3)>
    MyTest.objects.all()
    => [<MyTest(id=1, var=3)>, <MyTest(id=2, var=2)>]

I understand why this happens but not really how to correct it

PS : i use the latest version, but tried too without our recent "if not to_cache"

**Comment by tobiasmcnulty** [comment]
Hi @fdintino I'm helping Jeff out a bit and wanted to revisit this issue as a lot of the issues that had accumulated would be solved by a fix here. Do you have any bandwidth at present to help review and/or propose a PR to help resolve this? Many thanks!

**Comment by tobiasmcnulty** [comment]
Fix in PR #102
