### ISSUE TITLE
failed to invalidate query cache when add new record to the table

### ISSUE THREAD

**Issue by yifanw80** [django-cache-machine/django-cache-machine#62]
repo steps:
1. iterator all the objects in the model and fill the cache
for m in MyModel.objects.all(): foo(m)
2. save a new record in this model
MyModel().save()
3. the cache for the step 1 should be invalided, but it is not. And the iteration result is the same as the step1

I'm using the latest git version and the model decleartion looks like this:

class MyModel(caching.base.CachingMixin, models.Model):
     #.....
     #....
     objects = caching.base.CachingManager()

**Comment by syedsaqibali** [comment]
This bug is a major problem for my application. I posted a question to StackOverflow about it: http://stackoverflow.com/questions/28336559/bug-in-django-cachemachine-ignores-saving-of-model

Can anyone advise a workaround? When is this expected to be fixed?

**Comment by tobiasmcnulty** [comment]
Realize this was reported first, but closing in favor of #90 as it sounds like a fix may be in progress there.
