### ISSUE TITLE
Development server hangs

### ISSUE THREAD

**Issue by schacki** [django-cache-machine/django-cache-machine#63]
Hi all,

I do have a very strange issue:
1. I Have added the CachingMixin to my model ==> everything works fine
2. I have added the objects = CachingManager() to my model ==> all models validat, development server starts at the command line as expected. But it will not serve any browser requests (just hanging). Strange is that I can open the shell and and retrieve data through the model.

Any help is highly appreciated. I am not very confident to move this to production (event if it looks like it is working), as long I have not understood this issue. I also have no clue how to further debug.

Regards,
Juergen

**Comment by tobiasmcnulty** [comment]
What version of Django are you using, and are you still experiencing this issue? I saw something similar on Django 1.7 recently but I haven't been able to figure out what was going on yet. The issue occurred frequently but was not always consistent.

**Comment by tobiasmcnulty** [comment]
...and now I can no longer reproduce it.

**Comment by tobiasmcnulty** [comment]
I still can't reproduce this. Feel free to re-open if this is still an issue for you.
