### ISSUE TITLE
usage with django.test.TestCase rollback

### ISSUE THREAD

**Issue by keturn** [django-cache-machine/django-cache-machine#64]
After adding django-cache-machine to my application, I ran my tests with the LocMemCache backend. I got some test failures, objects having foreign key references that weren't supported by corresponding rows in the database table. I haven't written a minimal reproduction yet, but I strongly suspect this is what's happening:

* test 1 calls Foo.objects.get_or_create(name="foo"), creating "foo" in database and cache.
* test 1 completes, `django.test.TestCase` does a rollback of the database state, removing "foo" from database.
* test 2 calls Foo.objects.get_or_create(name="foo"), pulls "foo" from cache, though it does not exist in database.
* failure follows.

My tests do pass with the DummyCache backend. And they pass if I put a get_cache('default').clear() in the test's setUp method.

(Django 1.6.2, d-c-m commit 449861a6)

At the very least this could use some documentation. I think it could be sensible to have a TestCase base class that clears the django-cache-machine backend on TestCase.setUp(). Open to other ideas about how to best handle this.

**Comment by tobiasmcnulty** [comment]
This is an issue that's not specific to django-cache-machine: https://code.djangoproject.com/ticket/11505

If you're using a cache in your application, chances are you will want to clear that between each test regardless of what is being cached.
