### ISSUE TITLE
work with Redis problem

### ISSUE THREAD

**Issue by scott1028** [django-cache-machine/django-cache-machine#65]
I setup it with redis,
At my project launch up, it work fine. but it working about 1~2 hours later,
I push a data and insert into database, i found the redis monitor which print del cache command, but i access my model api by "get method api", it alwasy the cache data there are no new record existed.

**Comment by tobiasmcnulty** [comment]
Redis is only used for the flush lists, not caching, so you still need memcached installed. Hopefully that helps. If there's a specific issue you're encountering feel free to re-open.

**Comment by scott1028** [comment]
Thank you! I will try it.
