### ISSUE TITLE
InvalidCacheBackendError when using caching.backends.memcached.MemcachedCache

### ISSUE THREAD

**Issue by vkurup** [django-cache-machine/django-cache-machine#66]
Just got this error when using Django 1.6.5. I see a report that it's fixed in #44. Will there be a release with that fix available on PyPI soon?

**Comment by tobiasmcnulty** [comment]
Hi @vkurup :-)

This should be fixed in 0.8.1.

**Comment by vkurup** [comment]
Thanks! Looks like you've been busy here :)
