### ISSUE TITLE
Problem with deprecated memcached.CacheClass.

### ISSUE THREAD

**Issue by feler404** [django-cache-machine/django-cache-machine#74]
Django==1.6.5
django-cache-machine==0.8

Use django-cache-machine witch caching.backends.memcached.MemcachedCache I got:
AttributeError: 'module' object has no attribute 'CacheClass'

and found in Django 1.5:
class CacheClass(BaseMemcachedCache):
    def __init__(self, server, params):
        import warnings
        warnings.warn(
            "memcached.CacheClass has been split into memcached.MemcachedCache and memcached.PyLibMCCache. Please update your cache backend setting.",
            DeprecationWarning
        )
...

and 

if django.VERSION[:2] >= (1, 3):

    class MemcachedCache(InfinityMixin, memcached.MemcachedCache):
        pass

    class PyLibMCCache(InfinityMixin, memcached.PyLibMCCache):
        pass

don't work properly. On pip is old version.

**Comment by tobiasmcnulty** [comment]
This is fixed in 849fde035789cd0e22b661ce45c689a62e4cce1c and will get out in the next version.
