### ISSUE TITLE
Automatic Invalidation not happening in Django 1.7

### ISSUE THREAD

**Issue by DebauchedSloth** [django-cache-machine/django-cache-machine#75]
I have a very simple caching model which is inherits from CachingMixin.  When I call save() in Django 1.7 (to add a new instance), the cache is not invalidated (the new object does not show up in subsequent queries.)

When I switch back to Django 1.6, the same code works perfectly.  Pulling the CachingManager and using 1.7 also works.

I am on trunk.

**Comment by nsfyn55** [comment]
@DebauchedSloth any resolution on this? We are also experiencing invalidation issues.

**Comment by DebauchedSloth** [comment]
None for us.  We are (carefully) working around the issue and are avoiding
using cache-machine anywhere it is not already in use.

On Fri, Jan 23, 2015 at 11:25 AM, Art <notifications@github.com> wrote:

> @DebauchedSloth <https://github.com/DebauchedSloth> any resolution on
> this? We are also experiencing invalidation issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jbalogh/django-cache-machine/issues/75#issuecomment-71219336>
> .
>



-- 

Greg White
(781) 248-4852

**Comment by tobiasmcnulty** [comment]
This appears to be the same issue reported in #90
