### ISSUE TITLE
Django 1.6/1.7 compatible?

### ISSUE THREAD

**Issue by ajmax** [django-cache-machine/django-cache-machine#81]
I see commits to master around Django 1.7 fixes, but the only released version of Cache-machine is 1.5 yrs old.  Is there a planned upcoming release?

**Comment by integricho** [comment]
+1

**Comment by tushar-thantharate** [comment]
Does this package provides Django 1.7  support?

**Comment by ramusus** [comment]
+1

**Comment by zweizeichen** [comment]
+1

**Comment by lucasdavid** [comment]
+1

**Comment by lucasdavid** [comment]
:+1:

**Comment by tobiasmcnulty** [comment]
I just tagged a new minor release (0.8.1) with some of the recent changes, including support for Django 1.7 and Django 1.8. You can find it on PyPI and checkout the release notes on GitHub or RTD:

http://cache-machine.readthedocs.org/en/latest/releases.html#v0-8-1-2015-07-03
