### ISSUE TITLE
pip install django-cache-machine doesnt fetch the latest version

### ISSUE THREAD

**Issue by subramanyamVemu** [django-cache-machine/django-cache-machine#84]
If I download and install the package with git clone it works
but if we do a pip install django-cache-machine it doesnt work with Django version 1.7

**Comment by tobiasmcnulty** [comment]
Hi all - I just tagged a new minor release with some of the recent changes. You can find it on PyPI and checkout the release notes on GitHub or RTD:

http://cache-machine.readthedocs.org/en/latest/releases.html#v0-8-1-2015-07-03
