### ISSUE TITLE
Adding a new object to a model does not invalidate cached queries for that model

### ISSUE THREAD

**Issue by asketsus** [django-cache-machine/django-cache-machine#90]
Hi,

There are some opened issues talking about problems with invalidation. I've implemented a couple of tests which current django cache machine fails on it:

```python
def test_update_after_put(self):
        """ Test invalidation after do a put and insert in a previous cached filter """
        user1 = User.objects.create(name='John')
        user1.save()
        user2 = User.objects.create(name='Matt')
        user2.save()

        users = User.objects.filter(name__icontains='Jo')
        first_count = users.count()
        user2.name = 'Joseph'
        user2.save()
        users = User.objects.filter(name__icontains='Jo')
        assert users.count() == (first_count + 1)

    def test_update_after_post(self):
        """ Test invalidation after do a post and get again a list of a model """
        user1 = User.objects.create(name='Tom')
        user1.save()
        users = User.objects.all()
        initial_count = users.count()

        user2 = User.objects.create(name='Jerry')
        user2.save()
        users = User.objects.all()
        assert users.count() == (initial_count+1)
````

The problem here was being that django_cache_machine caches a Queryset and it is flushed only if some object associated with this queryset is changed. But if previously to the timeout, you do a update or create operation this queryset is not invalidated and returns older results.

I've forked this repo and create a new flush key associated to the model. It saves QS flush keys associated with the model. In this case, if new objects are created or updated all the queryset associated to the Model will be flushed.

It's not implemented any logical for filters, so we can flush some queryset which not be modified. 

You can found it here: https://github.com/asketsus/django-cache-machine It has passed Travis-CI (including new tests). 

Also this issue is fixed: https://github.com/jbalogh/django-cache-machine/issues/87

Related issue: https://github.com/jbalogh/django-cache-machine/issues/75
Related issue: https://github.com/jbalogh/django-cache-machine/issues/62

I've not sent a pull request due to these changes modify logical of caches. If you want to create a branch for me perfect :)

**Comment by syedsaqibali** [comment]
I pulled this branch but the problem I described here is persisting: http://stackoverflow.com/questions/28336559/bug-in-django-cachemachine-ignores-saving-of-model

Just an FYI, I ran the test suite and everything seems to pass (I think, but I'm not sure. It doesn't tell me how many failures there were). You can see my test results here: https://gist.github.com/syedsaqibali/cc28a5933471f008c097

**Comment by asketsus** [comment]
@syedsaqibali Please comment here if finally worked my fork, Only for the info if someone need it (and won't ignore this thread).

Regards :)

**Comment by tobiasmcnulty** [comment]
Hi @asketsus, this sounds like a good thing to get in. Do you want to send your changes as a PR? That will make it easier to comment on the code line by line. Thanks!

**Comment by tobiasmcnulty** [comment]
Also see an extended discussion about this issue in #6

**Comment by asketsus** [comment]
Hi @tobiasmcnulty! I am traveling right now, but ASAP i will send the changes as a PR. I'm using it right now and it works fine on my fork. I'll check the discussion :)

**Comment by tobiasmcnulty** [comment]
Sounds good, thanks! In particular it may not work to invalidate the entire model as that could be catastrophic for some high throughput applications.

**Comment by tobiasmcnulty** [comment]
@asketsus Actually, I'm going to close this issue in favor of #6 since there's a bit more history there. Let's continue the discussion there.
