### ISSUE TITLE
This project needs a maintainer.

### ISSUE THREAD

**Issue by jbalogh** [django-cache-machine/django-cache-machine#91]
### OSS project looking for a good home

I haven't worked in the Django world for a few years so I don't have any motivation to maintain this project. Most of the maintenance involves keeping up with the release cycle for Django.

**Comment by bashu** [comment]
I can adopt it

**Comment by aztrock** [comment]
I adopted

**Comment by dnozay** [comment]
@aztrock , @bashu , would be great if you tagged & released a newer version.

**Comment by rattrayalex** [comment]
Has this, indeed, been adopted?

**Comment by blag** [comment]
I can't really adopt it, but I do have some changes stacked up in my PR #95.

Changes:
* Cache ManyToMany relations
* Update code to Python 3
* Support for Django 1.8

**Comment by rattrayalex** [comment]
Wow, that's awesome @blag ! Maybe I can use this instead of django-cacheops after all... 
Wish I knew enough / had enough time to review this myself. 

@aztrock are you the new maintainer?

**Comment by timdawborn** [comment]
Awesome, @blag!

**Comment by timdawborn** [comment]
For the benefit of anyone else using the aforementioned PR, there are issues with the to do with the different instances of Django not generating the same cache key for the same data. Details are on the PR.

**Comment by tobiasmcnulty** [comment]
Should anyone care to give it a review, I have a PR for Python 3 support here: PR #101

**Comment by tobiasmcnulty** [comment]
Also, I just tagged a new minor release (0.8.1) with some of the recent changes. You can find it on PyPI and checkout the release notes on GitHub or RTD:

http://cache-machine.readthedocs.org/en/latest/releases.html#v0-8-1-2015-07-03
